#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-shapeless_2.12
Version  : 2.3.2
Release  : 1
URL      : https://github.com/milessabin/shapeless/archive/shapeless-2.3.2.tar.gz
Source0  : https://github.com/milessabin/shapeless/archive/shapeless-2.3.2.tar.gz
Source1  : https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.jar
Source2  : https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-shapeless_2.12-data = %{version}-%{release}

%description
# shapeless: generic programming for Scala
**shapeless** is a type class and dependent type based generic programming library for Scala. It had its origins in
several talks by Miles Sabin ([@milessabin][milessabin]), given over the course of 2011, on implementing [scrap your
boilerplate][syb] and [higher rank polymorphism][higherrank] in Scala. Since then it has evolved from being a resolutely
experimental project into library which, while still testing the limits of what's possible in Scala, is being used
widely in production systems wherever there are arities to be abstracted over and boilerplate to be scrapped.

%package data
Summary: data components for the mvn-shapeless_2.12 package.
Group: Data

%description data
data components for the mvn-shapeless_2.12 package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/chuusai/shapeless_2.12/2.3.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/chuusai/shapeless_2.12/2.3.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.jar
/usr/share/java/.m2/repository/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.pom
